server:
  port: 8080

management:
  info:
    git:
      mode: "full"
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

spring:
  cloud:
    stream:
      bindings:
        eins2zweiChannel: # INPUT
          destination: my.eins2zweiChannel # matching OUTPUT of sender
          group: zweiInputGroup
          contentType: text/plain
          
      default-binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: some-rabbit
                port: 5672

---

spring:
  profiles: local
  cloud:
    stream:
      default-binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672

---

spring:
  profiles: vm
  cloud:
    stream:
      default-binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.99.100
                port: 5672

